# Environment-specific parameters
trigger:
  branches:
    include:
    - master                              # REQUIRED, branch name

variables:
  buildConfiguration: 'Release'           # REQUIRED, config name


# Generic parameters
name: $(date:yyyyMMdd)$(rev:.r)

resources: 
  repositories: 
  - repository: SCE.Pipelines 
    name: SCE.Pipelines
    type: git 
    ref: master #branch name

jobs:
- template: net-core-nuget-build.pipeline.yml@SCE.Pipelines
  parameters:
    buildConFiguration: $(buildConfiguration)
